# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mike/Desktop/FinalProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mike/Desktop/FinalProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/Desktop/FinalProject/CMakeFiles /home/mike/Desktop/FinalProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/Desktop/FinalProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled

# Build rule for target.
untitled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled
.PHONY : untitled

# fast build rule for target.
untitled/fast:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/build
.PHONY : untitled/fast

ClipUtils.o: ClipUtils.cpp.o

.PHONY : ClipUtils.o

# target to build an object file
ClipUtils.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ClipUtils.cpp.o
.PHONY : ClipUtils.cpp.o

ClipUtils.i: ClipUtils.cpp.i

.PHONY : ClipUtils.i

# target to preprocess a source file
ClipUtils.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ClipUtils.cpp.i
.PHONY : ClipUtils.cpp.i

ClipUtils.s: ClipUtils.cpp.s

.PHONY : ClipUtils.s

# target to generate assembly for a file
ClipUtils.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ClipUtils.cpp.s
.PHONY : ClipUtils.cpp.s

RasterUtils.o: RasterUtils.cpp.o

.PHONY : RasterUtils.o

# target to build an object file
RasterUtils.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/RasterUtils.cpp.o
.PHONY : RasterUtils.cpp.o

RasterUtils.i: RasterUtils.cpp.i

.PHONY : RasterUtils.i

# target to preprocess a source file
RasterUtils.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/RasterUtils.cpp.i
.PHONY : RasterUtils.cpp.i

RasterUtils.s: RasterUtils.cpp.s

.PHONY : RasterUtils.s

# target to generate assembly for a file
RasterUtils.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/RasterUtils.cpp.s
.PHONY : RasterUtils.cpp.s

Rasterizer.o: Rasterizer.cpp.o

.PHONY : Rasterizer.o

# target to build an object file
Rasterizer.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Rasterizer.cpp.o
.PHONY : Rasterizer.cpp.o

Rasterizer.i: Rasterizer.cpp.i

.PHONY : Rasterizer.i

# target to preprocess a source file
Rasterizer.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Rasterizer.cpp.i
.PHONY : Rasterizer.cpp.i

Rasterizer.s: Rasterizer.cpp.s

.PHONY : Rasterizer.s

# target to generate assembly for a file
Rasterizer.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Rasterizer.cpp.s
.PHONY : Rasterizer.cpp.s

Sphere.o: Sphere.cpp.o

.PHONY : Sphere.o

# target to build an object file
Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Sphere.cpp.o
.PHONY : Sphere.cpp.o

Sphere.i: Sphere.cpp.i

.PHONY : Sphere.i

# target to preprocess a source file
Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Sphere.cpp.i
.PHONY : Sphere.cpp.i

Sphere.s: Sphere.cpp.s

.PHONY : Sphere.s

# target to generate assembly for a file
Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Sphere.cpp.s
.PHONY : Sphere.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... untitled"
	@echo "... ClipUtils.o"
	@echo "... ClipUtils.i"
	@echo "... ClipUtils.s"
	@echo "... RasterUtils.o"
	@echo "... RasterUtils.i"
	@echo "... RasterUtils.s"
	@echo "... Rasterizer.o"
	@echo "... Rasterizer.i"
	@echo "... Rasterizer.s"
	@echo "... Sphere.o"
	@echo "... Sphere.i"
	@echo "... Sphere.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

